fix: window窗口聚焦切换的问题
ayangweb/EcoPaste pull request #259
Opened 2024-07-30 03:40 UTC by ChurchTao

我提供一个思路，手头没有windows机器，你可以看下行不行，不行再说 哈哈哈

2024-07-30 03:44 UTC, ayangweb commented
佬，在 `show_window` 里面记录前一个窗口的思路是不行的，我刚开始 macos 也是这么做的，但是如果 pin 住剪切板，然后从 QQ 切换到微信，自动粘贴聚焦的依旧是 QQ！

2024-07-30 03:48 UTC, ChurchTao commented
哦 对哦，我忘了你前置条件就是pin住了

那我再看看这样的，https://learn.microsoft.com/zh-cn/windows/win32/api/winuser/nf-winuser-setwineventhook
<img width="765" alt="image" src="https://github.com/user-attachments/assets/22b008ca-897a-415f-847d-96303116b94c">

2024-07-30 03:51 UTC, ayangweb commented
好嘞，谢谢佬😘

2024-07-30 04:14 UTC, ChurchTao commented
@ayangweb 再看下，我改成了监听事件，有windows机器的小白鼠啊，帮我试试

2024-07-30 04:16 UTC, ayangweb commented
> @ayangweb 再看下，我改成了监听事件，有windows机器的小白鼠啊，帮我试试

OK，谢谢佬，我和 @kohaiy 来试试看！

2024-07-30 14:42 UTC, ayangweb commented
大佬，真是牛掰！刚从外面回来试了一下，稍微改了改，竟然成功了！现在的版本不抢占其他窗口的焦点，甚至支持文件重命名！奈何本人没文化，一句卧槽行天下🥳！

https://github.com/user-attachments/assets/ce178fe3-7fdc-4a8f-85ab-70ce92a83044

2024-07-30 14:50 UTC, ayangweb requested changes

2024-07-30 15:03 UTC, ChurchTao commented
@ayangweb
<img width="548" alt="image" src="https://github.com/user-attachments/assets/b9c90c73-c7d6-479f-9974-65f967d3dea2">
 我写的那个tode本意是留给你来写的，判断 （如果窗口句柄=剪贴板窗口句柄）则跳过，因为剪贴板这个窗口的句柄如果保存进去应该有bug，这个窗口句柄的缓存，就是为了保存最新的活动窗口，使得我们在切换到剪贴板上去执行命令时，能把之前的那个窗口激活，然后执行粘贴命令。你看着改吧

2024-08-02 05:07 UTC, ayangweb approved these changes

2024-08-02 05:11 UTC, merged